### ISSUE TITLE
pylint errors in django code

### ISSUE THREAD

**Issue by andreygalizin** [andrey-galizin/django-react-robin#1]
Issue:  pylint in VsCode is unable to import django.shortcuts and shows multiple 'errors' in code

**Comment by andreygalizin** [comment]
.pylintrc file was generated by running

    pylint --generate-rcfile > .pylintrc

in the generated .pyintrc file I edited this line to tell the linter to load django

# List of plugins (as comma separated values of python module names) to load,
# usually to register additional checkers.
load-plugins=django

**Comment by andrey-galizin** [comment]
This was fake issue, 
Solution 2: (open VS Code from an activated virtual environment):

    Open the terminal window
    Activate the relevant python virtual environment
    Ensure Pylint is installed within this virtual environment pip install pylint
    Close all instances of VS Code
    Launch VS Code from within this terminal window

(this will ensure the VS Code process will inherit all of the Virtual Env environment settings)

**Comment by andreygalizin** [comment]
This was fake issue,
Solution 2: (open VS Code from an activated virtual environment):

Open the terminal window
Activate the relevant python virtual environment
Ensure Pylint is installed within this virtual environment pip install pylint
Close all instances of VS Code
Launch VS Code from within this terminal window
(this will ensure the VS Code process will inherit all of the Virtual Env environment settings)
